name = "GREBClimate"
uuid = "128c3379-415a-4bc6-90bd-d536e37a6aec"
version = "2.1.0"
authors = ["Thomas Struys", "Michiel Stock", "Dietmar Dommenget and colleagues (original GREB)"]

[deps]
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
DataDeps = "1"
JLD2 = "0.6"
Logging = "1"
LoopVectorization = "0.12"
PrecompileTools = "1"
julia = "1.10"
