### Preset reference ###
#
# MAINTAINER TOOL - not part of the package. No dataset needed.
#
# Writes test/data/preset_reference.jl: what every experiment preset is
# (control CO2, CO2 masks, start year, output mode, loaded tables and table row,
# boundary forcing, the CO2 and solar multiplier over 150 scenario years, and
# its processes, hydrology and corrections), captured from the current code by
# test/support/presetcapture.jl. test/test_presets.jl checks
# the package against it. Regenerate only on purpose, when a preset is meant
# to change, and say so in the commit.
#
# Usage:
#   julia --project=. tools/validation/preset_reference.jl

using GREBClimate
const TEST = joinpath(@__DIR__, "..", "..", "test")
include(joinpath(TEST, "support", "testutils.jl"))
include(joinpath(TEST, "support", "presetcapture.jl"))

out = joinpath(TEST, "data", "preset_reference.jl")
mkpath(dirname(out))
open(out, "w") do io
    println(io, "# Generated by tools/validation/preset_reference.jl - do not edit by hand.")
    println(io, "const PRESET_REFERENCE = Dict{Symbol,Any}(")
    for p in PRESETS
        println(io, "    :$p => ", repr(capture_preset(p)), ",")
    end
    println(io, ")")
end
println("wrote $(length(PRESETS)) presets to $out ($(filesize(out)) bytes)")
